### PR TITLE
Added JSDoc and access modifiers

### PR DESCRIPTION
**Pull request by Gakuto1112**
Thank you for your recent response to my pull request (#2). Today, I will send you another poll request.

## Description
I added [JSDoc (JavaScript Document)](https://jsdoc.app/) and access modifiers.

### JSDoc
JSDoc is the comment of methods, variables, classes, and etc. which describes what they are or how they work. With this, module users can see descriptions when they use this module.

image

### Access modifiers
This is one of the [TypeScript](https://www.typescriptlang.org/) features. With this, we can set methods whether module uses can access those methods or not. We can prevent them from accessing unnecessary methods. Currently, only `open()`, `temperature()`, and `humidity()` are visible. If your intentions are different, feel free like to comment to this pull request.

image

Note that this is **only affected to TypeScript**. Although Private methods are still invisible in JavaScript, module users can access them.

image

image

## How to review
Just write some example codes in JavaScript or TypeScript. You can see the details of the methods and some method are invisible.

### CODE REVIEW

**Comment by thomome** [comment]
I'll make reset & calibrate public aswell. Could be something that's useful for others.

**Comment by Gakuto1112** [comment]
Thanks for your review. You said make `reset()` and `calibrate()` public. Will you change them your self?

**Comment by thomome** [comment]
Yes, I already adjusted it on develop.

**Comment by thomome** [comment]
Thanks again for your contribution! Proper types, errors & docs improves it a lot.

**Pull request merged**
